#!/usr/bin/env ruby
# frozen_string_literal: true

case ARGV
when %w[
  --list-target-files
]
  puts Dir['**/*.rb']
when %W[
  --require #{ENV['GITHUB_ACTION_PATH']}/rdjson_formatter/rdjson_formatter.rb
  --format RdjsonFormatter
  --fail-level error
]
  puts 'Mock message for reviewdog'
else
  abort "rubocop mock called with unexpected arguments:\n#{ARGV.join("\n")}"
end
