name: CI
on: [pull_request]
jobs:
  test-skip-install-and-use-bundler:
    name: runner / rubocop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/using_bundler
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test/using_bundler/Gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: rubocop with skip install and using bundler
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          skip_install: 'true'
          use_bundler: 'true'
      - run: test "$(bundle exec rubocop --version)" == "1.18.1"
